# Generated by Django 4.1.6 on 2023-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mive_app', '0002_movie_budget_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
