# Generated by Django 4.1.6 on 2023-02-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mive_app', '0006_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
