# Generated by Django 4.1.6 on 2023-02-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mive_app', '0009_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='mive_app.actor'),
        ),
    ]
